# Site settings
title: PRU
description: > # this means to ignore newlines until "url:"
  Performance monitoring data, analyses and visualizations for Eurocontrol's 41 Member States.
url: "http://ansperformance.eu" # the base hostname & protocol for your site; NO https if served by github pages!!!
canonical: "http://ansperformance.eu"  # NO https if served by github pages!!!
baseurl: "" # see https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
searchsites: "ansperformance.eu"

# Settings for deploy rake task
dest_user: euctrl-pru
dest_repo: euctrl-pru.github.io


media: media

include:
  - _pages

collections:
  studies:
    output: true

# Owner / Author information
owner:
  name: European Organisation for the Safety of Air Navigation (EUROCONTROL)
  location: Brussels, Belgium
  twitter: eurocontrol
  github:  euctrl-pru
  googleanalytics: UA-62697169-2
  email: PRU-Support@eurocontrol.int

webmaster:
  name: Enrico Spinielli
  email: enrico.spinielli [at] eurocontrol.int

tools:
  standards: "HTML5, SCSS"
  software: "Jekyll, pandoc, MathJax, d3.js, dc.js, crossfilter"

# Build settings
gems:
  - 'jekyll/scholar'
  - bootstrap-sass
  - uglifier
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
  - 'jekyll/figure'

assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/json
  css_compressor: sass
  js_compressor:  uglifier
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]
  digest: true

sass:
  sass_dir: _sass
  style: :compressed
  sourcemap: true
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

scholar:
  style: chicago-author-date
  locale: en
  source: references
  repository: references/library
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  bibtex_filters:
  - href
  - latex
  sort_by: year,month
  order: descending
  query: "@*"

# HTML Compression
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: development
  blanklines: true
  profile: false
  startings: [html, head, body]

# Global configs
timezone: Europe/Brussels

# don't deploy these folders/files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - "*.sql"
  - "references/*.bib"
  - tmp
  - references/auto
  - node_modules
  - package.json
  - npm-debug.log
  - scripts
  - vendor
  - .travis.yml
  - "data/set/*/extract_*"
  - "*.py"
  - R/
  - website.Rproj
  - .Rhistory
